repos:
#- repo: local
#  hooks:
#  - id: pytest
#    name: Check pytest unit tests pass
#    entry: bash -c "PYTHONPATH=. pytest"
#    pass_filenames: false
#    language: system
#    types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4 # Ruff version
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --extend-select, I]
      # Run the formatter
      - id: ruff-format

