name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install venv and dependencies with uv
        run: uv sync

      - name: Lint and format with Ruff
        run: |
          uv run ruff check . && ruff format .

#      - name: Run tests
#        run: |
#          uv run tests/runtests
